### ISSUE TITLE
Assertion error when running example code

### ISSUE THREAD

**Issue by cyrusmaher** [salesforce/progen#2]
Thanks for all your hard work in getting this out! I get the error below when running the example likelihood calculation.

Also, I wonder if you could comment on the example itself? I didn't find homology to a known protein when I blasted the sequence below, and it appears to begin with an "end-of-sequence" token, and end with a "beginning-of-sequence" token.

```
python3 likelihood.py --model progen2-small --context "2PAQGRARLAAHYGTGRIGREVTVDERCRNLDRLEPSWELLRLLDDMGFIEGQNGLRRYVAEVFALDEPYDMTWRLRSLDEPHEVNAIEFAAPHERVYATLSERFFPDSVERDLRELVTRSLVEVDLGDPFTPPFVNSVYELRGASRRWVGVVRDVLAPDVLPCDATIRVLADAGTRAATRGLREILDTESGRVCVLGLHAALDAIADDRNEVSTSVAVADLEQCVALREAIRQITPRGAISVLVKGPLRTSGMRAQIAAVVHLRAKSSHLLPGGTDVVTFGAREFAIRSAANERKVVASMRLLALPGFAERSLCGLARPGVGRGRWEPAINVSVAADRDQIDLRVMGADVGDASVIFLKRDFRKLTEEFWRTHTDVPIEREDVSAQRTEPDNRWRWLVPCDDLVAPRLTVVPPRSVGHGM1"
loading parameters
loading parameters took 5.17s
loading tokenizer
loading tokenizer took 0.00s
sanity log-likelihood
ll_0=-3.6930243968963623
ll_1=-3.7106473445892334
ll_2=-3.7106471061706543
sanity log-likelihood took 0.11s
Traceback (most recent call last):
  File "likelihood.py", line 226, in <module>
    main()
  File "likelihood.py", line 183, in main
    assert abs(ll_0 - ll_1) < 1e-2
AssertionError
```

**Comment by enijkamp** [comment]
@cyrusmaher These were numerical sanity checks. I added a default flag to disable those. The model is trained with observations in both 1...2 and 2...1 order.

Does this help?

**Comment by a-mad** [comment]
@cyrusmaher , the example sequence was flipped (i.e. tokens/residues are arranged from C-terminus to N-terminus). `1` corresponds to N-terminus, `2` corresponds to C-terminus. if you blast the reversed version, you'll get a 100% hit for GenBank: TMF32756.1:
 `1MGHGVSRPPVVTLRPAVLDDCPVLWRWRNDPETRQASVDEREIPVDTHTRWFEETLKRFDRKLFIVSADGVDAGMVRLDIQDRDAAVSVNIAPEWRGRGVGPRALGCLSREAFGPLALLRMSAVVKRENAASRIAFERAGFTVVDTGGPLLHSSKARLHVVAAIQARMGSTRLPGKVLVSIAGRPTIQRIAERLAVCQELDAVAVSTSVENRDDAIADLAAHLGLVCVRGSETDLIERLGRTAARTGADALVRITADCPLVDPALVDRVVGVWRRSAGRLEYVSNVFPPTFPDGLDVEVLSRTVLERLDREVSDPFFRESLTAYVREHPAAFEIANVEHPEDLSRLRWTMDYPEDLAFVEAVYRRLGNQGEIFGMDDLLRLLEWSPELRDLNRCREDVTVERGIRGTGYHAALRARGQAP2`
 
This is understandably confusing. We can change the example sequence to a more relatable protein that is arranged the standard/biophysically-consistent manner (N->C).
 
But practically, please note when you rank variants... use the average LL of the sequence in both directions. You'll get the best results this way.

**Comment by enijkamp** [comment]
@cyrusmaher We have pushed a few corrections and sanity checks. The implementation should now behave identical to the one used for the reported results.

Could you try once more? Does this help?
