### ISSUE TITLE
how to run log likelihood score script on a 2 chain protein?

### ISSUE THREAD

**Issue by avilella** [salesforce/progen#5]
Is there a way to specify a 2 chain protein (e.g. an antibody Fv) as the input of the `likelihood.py` script? E.g. separating the two chains by a semi-colon or a colon or something like that? Thx in advance.

**Comment by a-mad** [comment]
specifying a linker (e.g. any combination of glycine-serine flexible linkers) between the two domains works well empirically

for your antibody use-case, i'd go with (GGGGS)x3

**Comment by a-mad** [comment]
@avilella can you close this issue, if it's satisfactory?
